# Data Preparation and Cleaning

#### The dataset used is the 2016,2018 and 2020 Behavioral Risk Factor Surveillance System (BRFSS) data provided by the Centers for Disease Control and Prevention (CDC), a national public health agency of the United States. 
#### The chosen dataset contains records of the surveys conducted through landline and cellular telephone. According to CDC, the BRFSS's aims to collect data about chronic diseases and conditions, health risk behaviors, accessibility to health care facilities, and use of health services related to causes of disability and death.
Dataset source url: <br>
https://www.cdc.gov/brfss/annual_data/annual_2020.html <br>
https://www.kaggle.com/datasets/sakinak/behavioral-risk-factor-surveillance-survey-201619

#### There are too many variables in the dataset. Hence, we decided to filter the dataset and select the variables that are more important for the diseases we are studying. 
The variables are chosen with reference to this source stating the risk factors that contributes to heart diseases: <br>
https://www.webmd.com/heart-disease/risk-factors-for-heart-disease

### Importing essential libraries

In [1]:
# Import basic libraries
import numpy as np
import pandas as pd
import seaborn as sb

### Cleaning the 2016 Dataset

In [2]:
raw_data_2016 = pd.read_csv('Data/2016_Data.csv', low_memory=False)
raw_data_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486303 entries, 0 to 486302
Columns: 276 entries, Unnamed: 0 to _AIDTST3
dtypes: float64(227), int64(48), object(1)
memory usage: 1.0+ GB


In [3]:
selected_data_2016  =  raw_data_2016[['_AGE_G'   , 'SEX'     , 'HTM4'     , 'WTKG3'    , '_BMI5'    , 'MARITAL'  ,
                                      '_INCOMG'  , '_EDUCAG' , 'GENHLTH'  , 'PHYSHLTH' , 'MENTHLTH' , 'SLEPTIM1' ,
                                      '_SMOKER3' , '_MICHD'  , 'CVDSTRK3' , 'ADDEPEV2' , 'CHCKIDNY' , 'CHCOCNCR' ,
                                      '_DRDXAR1' , 'CHECKUP1', 'PDIABTST' , '_TOTINDA' , 'DIABETE3' , '_RFDRHV5' ]]

In [4]:
selected_data_2016 = selected_data_2016.dropna()
selected_data_2016.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 174298 entries, 0 to 486302
Data columns (total 24 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   _AGE_G    174298 non-null  int64  
 1   SEX       174298 non-null  int64  
 2   HTM4      174298 non-null  float64
 3   WTKG3     174298 non-null  float64
 4   _BMI5     174298 non-null  float64
 5   MARITAL   174298 non-null  float64
 6   _INCOMG   174298 non-null  int64  
 7   _EDUCAG   174298 non-null  int64  
 8   GENHLTH   174298 non-null  float64
 9   PHYSHLTH  174298 non-null  float64
 10  MENTHLTH  174298 non-null  float64
 11  SLEPTIM1  174298 non-null  float64
 12  _SMOKER3  174298 non-null  int64  
 13  _MICHD    174298 non-null  float64
 14  CVDSTRK3  174298 non-null  float64
 15  ADDEPEV2  174298 non-null  float64
 16  CHCKIDNY  174298 non-null  float64
 17  CHCOCNCR  174298 non-null  float64
 18  _DRDXAR1  174298 non-null  float64
 19  CHECKUP1  174298 non-null  float64
 20  PDIA

In [5]:
selected_data_2016['_AGE_G'] = selected_data_2016['_AGE_G'].astype('category')
selected_data_2016['_AGE_G'].unique()

[3, 5, 6, 1, 4, 2]
Categories (6, int64): [1, 2, 3, 4, 5, 6]

In [6]:
selected_data_2016['HTM4'].unique()

array([173., 160., 165., 168., 155., 183., 157., 175., 170., 178., 163.,
       180., 198., 191., 150., 152., 196., 188., 193., 147., 185., 142.,
       145., 203., 201., 172., 135., 132., 224., 162., 107., 176., 156.,
       153., 122., 140., 130., 164., 206., 127.,  91., 174., 184., 167.,
       159., 208., 177., 211., 199., 161., 182., 148., 194., 143., 166.,
       154., 102., 171., 190., 149., 179., 158., 200., 189., 151., 186.,
       169., 181., 137., 105., 104., 213., 124., 146., 114., 216., 221.,
       119., 103., 187., 101., 106., 144., 110., 229.])

In [7]:
selected_data_2016['WTKG3'] = selected_data_2016['WTKG3'].div(100).round(0)
selected_data_2016['WTKG3'].unique()

array([ 61.,  69.,  54.,  57.,  59.,  91., 104.,  56.,  83.,  68.,  65.,
        77.,  66.,  96.,  98.,  64.,  86., 118.,  73., 111.,  75.,  81.,
       102., 136., 141., 108.,  67.,  89.,  70.,  79.,  88.,  58., 100.,
       107., 109.,  50.,  78.,  82.,  72., 127.,  95.,  48.,  74., 116.,
       113.,  84.,  71., 151.,  45., 103.,  93.,  60.,  99., 120.,  87.,
        80., 122.,  44.,  76.,  53.,  63.,  97.,  90.,  52., 159.,  55.,
        62.,  51.,  85.,  92., 114.,  49.,  46., 132., 163., 126.,  34.,
        47.,  43., 152., 106., 154.,  42., 112.,  94.,  39., 121., 105.,
       119., 125.,  41., 129., 135., 133., 101., 138., 168., 139.,  38.,
       214., 172., 145., 124., 150., 147., 110., 128., 170., 117., 140.,
       169., 115., 166.,  37., 144., 142., 131., 143., 130., 134.,  35.,
       161., 209.,  40.,  36., 158., 165., 137., 195., 123., 155., 200.,
       181., 177.,  33.,  30., 212., 184., 156., 187., 174., 182., 226.,
       167., 160., 148., 175., 171., 198., 194., 15

In [8]:
selected_data_2016['_BMI5'] = selected_data_2016['_BMI5'].div(100).round(0)
selected_data_2016['_BMI5'].unique()

array([ 21.,  27.,  20.,  25.,  32.,  31.,  23.,  26.,  28.,  30.,  34.,
        24.,  22.,  36.,  40.,  29.,  41.,  35.,  39.,  42.,  37.,  44.,
        19.,  33.,  18.,  38.,  43.,  52.,  60.,  47.,  15.,  17.,  16.,
        48.,  45.,  51.,  46.,  14.,  58.,  49.,  62.,  50.,  59.,  55.,
        57.,  54.,  68.,  13.,  56.,  70.,  61.,  64.,  63.,  53.,  69.,
        65.,  76.,  71.,  67.,  86.,  72.,  87.,  73.,  75.,  89.,  12.,
        78., 100.,  77.,  66.,  81.,  74.,  82.,  85.,  91.,  97.,  95.,
        83.,  79.,  80.,  94.])

In [9]:
selected_data_2016 = selected_data_2016[selected_data_2016['MARITAL'] != 9]
selected_data_2016['MARITAL'] = selected_data_2016['MARITAL'].astype('category')
selected_data_2016['MARITAL'].unique()

C:\Users\Shan\anaconda3\lib\site-packages\pandas\io\formats\format.py:1429: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  for val, m in zip(values.ravel(), mask.ravel())


[1.0, 3.0, 5.0, 2.0, 6.0, 4.0]
Categories (6, float64): [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [10]:
selected_data_2016 = selected_data_2016[selected_data_2016['_INCOMG'] != 9]
selected_data_2016['_INCOMG'] = selected_data_2016['_INCOMG'].astype('category')
selected_data_2016['_INCOMG'].unique()

[3, 5, 4, 1, 2]
Categories (5, int64): [1, 2, 3, 4, 5]

In [11]:
selected_data_2016 = selected_data_2016[selected_data_2016['_EDUCAG'] != 9]
selected_data_2016['_EDUCAG'] = selected_data_2016['_EDUCAG'].astype('category')
selected_data_2016['_EDUCAG'].unique()

[2, 3, 4, 1]
Categories (4, int64): [1, 2, 3, 4]

In [12]:
selected_data_2016 = selected_data_2016[selected_data_2016['GENHLTH'] != 7]
selected_data_2016 = selected_data_2016[selected_data_2016['GENHLTH'] != 9]
selected_data_2016['GENHLTH'] = selected_data_2016['GENHLTH'].astype('category')
selected_data_2016['GENHLTH'].unique()

[1.0, 2.0, 3.0, 4.0, 5.0]
Categories (5, float64): [1.0, 2.0, 3.0, 4.0, 5.0]

In [13]:
selected_data_2016['MENTHLTH'] = selected_data_2016['MENTHLTH'].replace({88:0})
selected_data_2016 = selected_data_2016[selected_data_2016['MENTHLTH'] != 77]
selected_data_2016 = selected_data_2016[selected_data_2016['MENTHLTH'] != 99]
selected_data_2016['MENTHLTH'].unique()

array([ 0.,  1.,  5.,  3.,  2., 15.,  4., 20., 30., 25.,  7.,  8., 10.,
       12., 29., 13.,  6., 16., 22., 14., 28., 18., 21., 23., 17., 24.,
       27.,  9., 11., 19., 26.])

In [14]:
selected_data_2016['PHYSHLTH'] = selected_data_2016['PHYSHLTH'].replace({88:0})
selected_data_2016 = selected_data_2016[selected_data_2016['PHYSHLTH'] != 77]
selected_data_2016 = selected_data_2016[selected_data_2016['PHYSHLTH'] != 99]
selected_data_2016['PHYSHLTH'].unique()

array([ 0., 20.,  6.,  7.,  4.,  1., 14.,  2., 10., 30., 25., 21.,  3.,
        5., 15., 28.,  9., 12., 29., 26., 17.,  8., 18., 16., 23., 27.,
       13., 19., 11., 24., 22.])

In [15]:
selected_data_2016 = selected_data_2016[selected_data_2016['SLEPTIM1'] != 77]
selected_data_2016 = selected_data_2016[selected_data_2016['SLEPTIM1'] != 99]
selected_data_2016['SLEPTIM1'].unique()

array([ 5.,  6.,  9.,  8.,  7.,  4., 10., 12.,  2.,  3., 15., 14., 16.,
       11., 18., 17., 13.,  1., 20., 24., 21., 22., 19., 23.])

In [16]:
selected_data_2016['_MICHD'] = selected_data_2016['_MICHD'].replace({2:0})
selected_data_2016['_MICHD'] = selected_data_2016['_MICHD'].astype('category')
selected_data_2016['_MICHD'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [17]:
selected_data_2016['CVDSTRK3'] = selected_data_2016['CVDSTRK3'].replace({2:0})
selected_data_2016 = selected_data_2016[selected_data_2016['CVDSTRK3'] != 7]
selected_data_2016 = selected_data_2016[selected_data_2016['CVDSTRK3'] != 9]
selected_data_2016['CVDSTRK3'] = selected_data_2016['CVDSTRK3'].astype('category')
selected_data_2016['CVDSTRK3'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [18]:
selected_data_2016['ADDEPEV2'] = selected_data_2016['ADDEPEV2'].replace({2:0})
selected_data_2016 = selected_data_2016[selected_data_2016['ADDEPEV2'] != 7]
selected_data_2016 = selected_data_2016[selected_data_2016['ADDEPEV2'] != 9]
selected_data_2016['ADDEPEV2'] = selected_data_2016['ADDEPEV2'].astype('category')
selected_data_2016['ADDEPEV2'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [19]:
selected_data_2016['CHCKIDNY'] = selected_data_2016['CHCKIDNY'].replace({2:0})
selected_data_2016 = selected_data_2016[selected_data_2016['CHCKIDNY'] != 7]
selected_data_2016 = selected_data_2016[selected_data_2016['CHCKIDNY'] != 9]
selected_data_2016['CHCKIDNY'] = selected_data_2016['CHCKIDNY'].astype('category')
selected_data_2016['CHCKIDNY'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [20]:
selected_data_2016['DIABETE3'] = selected_data_2016['DIABETE3'].replace({2:0, 3:0, 1:1, 4:1})
selected_data_2016 = selected_data_2016[selected_data_2016['DIABETE3'] != 7]
selected_data_2016 = selected_data_2016[selected_data_2016['DIABETE3'] != 9]
selected_data_2016['DIABETE3'] = selected_data_2016['DIABETE3'].astype('category')
selected_data_2016['DIABETE3'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [21]:
selected_data_2016['_DRDXAR1'] = selected_data_2016['_DRDXAR1'].replace({2:0})
selected_data_2016['_DRDXAR1'] = selected_data_2016['_DRDXAR1'].astype('category')
selected_data_2016['_DRDXAR1'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [22]:
selected_data_2016  = selected_data_2016[selected_data_2016['CHECKUP1'] != 7]
selected_data_2016  = selected_data_2016[selected_data_2016['CHECKUP1'] != 8]
selected_data_2016  = selected_data_2016[selected_data_2016['CHECKUP1'] != 9]
selected_data_2016['CHECKUP1'] = selected_data_2016['CHECKUP1'].astype('category')
selected_data_2016['CHECKUP1'].unique()

[1.0, 3.0, 2.0, 4.0]
Categories (4, float64): [1.0, 2.0, 3.0, 4.0]

In [23]:
selected_data_2016['PDIABTST'] = selected_data_2016['PDIABTST'].replace({2:0})
selected_data_2016 = selected_data_2016[selected_data_2016['PDIABTST'] != 7]
selected_data_2016 = selected_data_2016[selected_data_2016['PDIABTST'] != 9]
selected_data_2016['PDIABTST'] = selected_data_2016['PDIABTST'].astype('category')
selected_data_2016.PDIABTST.unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [24]:
selected_data_2016['_TOTINDA'] = selected_data_2016['_TOTINDA'].replace({2:0})
selected_data_2016 = selected_data_2016[selected_data_2016['_TOTINDA'] != 9]
selected_data_2016['_TOTINDA'] = selected_data_2016['_TOTINDA'].astype('category')
selected_data_2016['_TOTINDA'].unique()

[1, 0]
Categories (2, int64): [0, 1]

In [25]:
selected_data_2016 = selected_data_2016[selected_data_2016['_SMOKER3'] != 9]
selected_data_2016['_SMOKER3'] = selected_data_2016['_SMOKER3'].astype('category')
selected_data_2016['_SMOKER3'].unique()

[4, 1, 3, 2]
Categories (4, int64): [1, 2, 3, 4]

In [26]:
selected_data_2016['_RFDRHV5'] = selected_data_2016['_RFDRHV5'].replace({2:0})
selected_data_2016 = selected_data_2016[selected_data_2016['_RFDRHV5'] != 9]
selected_data_2016['_RFDRHV5'] = selected_data_2016['_RFDRHV5'].astype('category')
selected_data_2016['_RFDRHV5'].unique()

[1, 0]
Categories (2, int64): [0, 1]

In [27]:
selected_data_2016['CHCOCNCR'] = selected_data_2016['CHCOCNCR'].replace({2:0})
selected_data_2016 = selected_data_2016[selected_data_2016['CHCOCNCR'] != 7]
selected_data_2016 = selected_data_2016[selected_data_2016['CHCOCNCR'] != 9]
selected_data_2016['CHCOCNCR'] = selected_data_2016['CHCOCNCR'].astype('category')
selected_data_2016['CHCOCNCR'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [28]:
selected_data_2016.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 132556 entries, 1 to 486302
Data columns (total 24 columns):
 #   Column    Non-Null Count   Dtype   
---  ------    --------------   -----   
 0   _AGE_G    132556 non-null  category
 1   SEX       132556 non-null  int64   
 2   HTM4      132556 non-null  float64 
 3   WTKG3     132556 non-null  float64 
 4   _BMI5     132556 non-null  float64 
 5   MARITAL   132556 non-null  category
 6   _INCOMG   132556 non-null  category
 7   _EDUCAG   132556 non-null  category
 8   GENHLTH   132556 non-null  category
 9   PHYSHLTH  132556 non-null  float64 
 10  MENTHLTH  132556 non-null  float64 
 11  SLEPTIM1  132556 non-null  float64 
 12  _SMOKER3  132556 non-null  category
 13  _MICHD    132556 non-null  category
 14  CVDSTRK3  132556 non-null  category
 15  ADDEPEV2  132556 non-null  category
 16  CHCKIDNY  132556 non-null  category
 17  CHCOCNCR  132556 non-null  category
 18  _DRDXAR1  132556 non-null  category
 19  CHECKUP1  132556 non-nu

### Cleaning the 2018 Dataset

In [29]:
raw_data_2018 = pd.read_csv('Data/2018_Data.csv', low_memory=False)
raw_data_2018.head()

Unnamed: 0  _STATE  FMONTH    IDATE  IMONTH  IDAY  IYEAR  DISPCODE  \
0           1       1       1  1052018       1     5   2018      1100   
1           2       1       1  1122018       1    12   2018      1100   
2           3       1       1  1082018       1     8   2018      1100   
3           4       1       1  1032018       1     3   2018      1100   
4           5       1       1  1122018       1    12   2018      1100   

        SEQNO        _PSU  ...  _MAM5022  _RFPAP34  _RFPSA22  _RFBLDS3  \
0  2018000001  2018000001  ...       NaN       NaN       NaN       NaN   
1  2018000002  2018000002  ...       NaN       1.0       NaN       NaN   
2  2018000003  2018000003  ...       NaN       NaN       NaN       NaN   
3  2018000004  2018000004  ...       NaN       NaN       2.0       2.0   
4  2018000005  2018000005  ...       NaN       NaN       NaN       NaN   

   _COL10YR  _HFOB3YR  _FS5YR  _FOBTFS  _CRCREC  _AIDTST3  
0       NaN       NaN     NaN      NaN      NaN       2.0  
1       NaN       NaN     NaN      NaN      NaN       2.0  
2       NaN       NaN     NaN      NaN      NaN       2.0  
3       2.0       2.0     2.0      2.0      2.0       2.0  
4       NaN       NaN     NaN      NaN      NaN       2.0  

[5 rows x 276 columns]

In [30]:
selected_data_2018  =  raw_data_2018[['_AGE_G'   , 'SEX1'     , 'HTM4'     , 'WTKG3'    , '_BMI5'    , 'MARITAL'  ,
                                      '_INCOMG'  , '_EDUCAG' , 'GENHLTH'  , 'PHYSHLTH' , 'MENTHLTH' , 'SLEPTIM1' ,
                                      '_SMOKER3' , '_MICHD'  , 'CVDSTRK3' , 'ADDEPEV2' , 'CHCKDNY1' , 'CHCOCNCR' ,
                                      '_DRDXAR1' , 'CHECKUP1', 'PDIABTST' , '_TOTINDA' , 'DIABETE3' , '_RFDRHV6' ]]

In [31]:
selected_data_2018 = selected_data_2018.dropna()
selected_data_2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 184118 entries, 0 to 437435
Data columns (total 24 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   _AGE_G    184118 non-null  int64  
 1   SEX1      184118 non-null  int64  
 2   HTM4      184118 non-null  float64
 3   WTKG3     184118 non-null  float64
 4   _BMI5     184118 non-null  float64
 5   MARITAL   184118 non-null  float64
 6   _INCOMG   184118 non-null  int64  
 7   _EDUCAG   184118 non-null  int64  
 8   GENHLTH   184118 non-null  float64
 9   PHYSHLTH  184118 non-null  float64
 10  MENTHLTH  184118 non-null  float64
 11  SLEPTIM1  184118 non-null  float64
 12  _SMOKER3  184118 non-null  int64  
 13  _MICHD    184118 non-null  float64
 14  CVDSTRK3  184118 non-null  float64
 15  ADDEPEV2  184118 non-null  float64
 16  CHCKDNY1  184118 non-null  float64
 17  CHCOCNCR  184118 non-null  float64
 18  _DRDXAR1  184118 non-null  float64
 19  CHECKUP1  184118 non-null  float64
 20  PDIA

In [32]:
selected_data_2018['_AGE_G'] = selected_data_2018['_AGE_G'].astype('category')
selected_data_2018['_AGE_G'].unique()

[6, 2, 4, 5, 3, 1]
Categories (6, int64): [1, 2, 3, 4, 5, 6]

In [33]:
selected_data_2018['SEX1'] = selected_data_2018['SEX1'].replace({2:0})
selected_data_2018 = selected_data_2018[selected_data_2018['SEX1'] != 9]
selected_data_2018 = selected_data_2018[selected_data_2018['SEX1'] != 7]
selected_data_2018['SEX1'] = selected_data_2018['SEX1'].astype('category')
#selected_data_2016['SEX'] = selected_data_2016['SEX1'].cat.rename_categories({"Female":"F"})
selected_data_2018['SEX1'].unique()

[0, 1]
Categories (2, int64): [0, 1]

In [34]:
selected_data_2018['HTM4'].unique()

array([163., 165., 178., 157., 160., 183., 180., 168., 185., 170., 175.,
       173., 188., 152., 147., 155., 191., 142., 201., 150., 193., 196.,
       132., 145., 203., 137., 198., 211., 216., 206., 208., 130., 140.,
       156., 135., 154., 176., 105., 162., 218., 159., 179., 104., 172.,
       177., 124., 122., 192., 164., 161., 186., 181., 167., 108., 111.,
       127.,  91., 213., 184., 107., 119., 166., 187., 114., 174., 110.,
       158., 153., 149., 169., 190., 221., 151., 189., 205., 148., 226.,
       146., 241., 182., 100., 171., 120., 234., 106., 125., 102., 229.,
       236., 136., 103., 109., 128.,  94.])

In [35]:
selected_data_2018['WTKG3'] = selected_data_2018['WTKG3'].div(100).round(0)
selected_data_2018['WTKG3'].unique()

array([ 59.,  91.,  86.,  78.,  68.,  90.,  77.,  73., 129.,  98., 113.,
        70.,  63., 109.,  84.,  75.,  54.,  82.,  58.,  67.,  66., 131.,
        69., 136.,  76., 125.,  80.,  57.,  64.,  79.,  93.,  61.,  72.,
       105.,  85., 102.,  95.,  83., 100., 104.,  37., 108.,  88.,  94.,
       122.,  43.,  48.,  97.,  53., 106.,  74., 127.,  56.,  51., 115.,
        39.,  71.,  92.,  50.,  45., 103.,  96.,  62., 132., 118.,  65.,
        89., 159.,  52.,  60., 101.,  38.,  81.,  49., 150.,  99.,  87.,
        55., 117., 120., 107., 141.,  44., 145.,  47., 124., 110., 134.,
       111., 128., 154., 168., 227., 146.,  41., 143.,  40.,  42., 116.,
       147., 126., 123., 119.,  46.,  36., 130., 157., 172., 181., 112.,
       144., 114., 152., 197., 142., 138., 186., 149., 148., 193., 135.,
       283., 175., 176.,  34., 173., 208., 163., 229., 204., 200., 155.,
       166., 121., 151., 195., 170., 137., 167., 140., 133., 158., 220.,
       139., 156., 190., 182., 188., 183., 177.,  3

In [36]:
selected_data_2018['_BMI5'] = selected_data_2018['_BMI5'].div(100).round(0)
selected_data_2018['_BMI5'].unique()

array([22., 33., 27., 31., 25., 30., 28., 40., 35., 24., 38., 21., 26.,
       23., 48., 29., 37., 41., 34., 32., 15., 19., 39., 16., 18., 20.,
       36., 17., 43., 53., 44., 42., 57., 47., 46., 45., 52., 49., 50.,
       56., 54., 55., 14., 58., 77., 62., 65., 78., 63., 13., 59., 84.,
       61., 60., 51., 81., 66., 70., 64., 68., 74., 69., 67., 94., 83.,
       86., 90., 76., 79., 12., 92., 98., 75., 71., 72., 73., 87., 97.,
       82., 96., 80., 99., 89., 95., 88.])

In [37]:
selected_data_2018 = selected_data_2018[selected_data_2018['MARITAL'] != 9]
selected_data_2018['MARITAL'] = selected_data_2018['MARITAL'].astype('category')
selected_data_2018['MARITAL'].unique()

C:\Users\Shan\anaconda3\lib\site-packages\pandas\io\formats\format.py:1429: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  for val, m in zip(values.ravel(), mask.ravel())


[3.0, 5.0, 2.0, 1.0, 4.0, 6.0]
Categories (6, float64): [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [38]:
selected_data_2018 = selected_data_2018[selected_data_2018['_INCOMG'] != 9]
selected_data_2018['_INCOMG'] = selected_data_2018['_INCOMG'].astype('category')
selected_data_2018['_INCOMG'].unique()

[4, 2, 5, 3, 1]
Categories (5, int64): [1, 2, 3, 4, 5]

In [39]:
selected_data_2018 = selected_data_2018[selected_data_2018['_EDUCAG'] != 9]
selected_data_2018['_EDUCAG'] = selected_data_2018['_EDUCAG'].astype('category')
selected_data_2018['_EDUCAG'].unique()

[4, 2, 3, 1]
Categories (4, int64): [1, 2, 3, 4]

In [40]:
selected_data_2018 = selected_data_2018[selected_data_2018['GENHLTH'] != 7]
selected_data_2018 = selected_data_2018[selected_data_2018['GENHLTH'] != 9]
selected_data_2018['GENHLTH'] = selected_data_2018['GENHLTH'].astype('category')
selected_data_2018['GENHLTH'].unique()

[2.0, 3.0, 1.0, 5.0, 4.0]
Categories (5, float64): [1.0, 2.0, 3.0, 4.0, 5.0]

In [41]:
selected_data_2018['MENTHLTH'] = selected_data_2018['MENTHLTH'].replace({88:0})
selected_data_2018 = selected_data_2018[selected_data_2018['MENTHLTH'] != 77]
selected_data_2018 = selected_data_2018[selected_data_2018['MENTHLTH'] != 99]
selected_data_2018['MENTHLTH'].unique()

array([ 0.,  2.,  1., 30., 10., 20.,  3., 15.,  4., 28., 21.,  7.,  5.,
       25., 14.,  6.,  8., 12., 11.,  9., 16., 27., 18., 19., 13., 29.,
       26., 22., 17., 23., 24.])

In [42]:
selected_data_2018['PHYSHLTH'] = selected_data_2018['PHYSHLTH'].replace({88:0})
selected_data_2018 = selected_data_2018[selected_data_2018['PHYSHLTH'] != 77]
selected_data_2018 = selected_data_2018[selected_data_2018['PHYSHLTH'] != 99]
selected_data_2018['PHYSHLTH'].unique()

array([30.,  0.,  5.,  7.,  2.,  3., 10.,  1., 20., 14.,  4., 15., 17.,
       25., 29., 18.,  6.,  8.,  9., 12., 21., 24., 28., 23., 11., 13.,
       16., 26., 22., 27., 19.])

In [43]:
selected_data_2018 = selected_data_2018[selected_data_2018['SLEPTIM1'] != 77]
selected_data_2018 = selected_data_2018[selected_data_2018['SLEPTIM1'] != 99]
selected_data_2018['SLEPTIM1'].unique()

array([ 7.,  5.,  6.,  8., 10.,  9., 12.,  4., 14., 18.,  3., 15., 11.,
        1., 20., 16., 13.,  2., 21., 23., 17., 24., 19., 22.])

In [44]:
selected_data_2018['_MICHD'] = selected_data_2018['_MICHD'].replace({2:0})
selected_data_2018['_MICHD'] = selected_data_2018['_MICHD'].astype('category')
selected_data_2018['_MICHD'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [45]:
selected_data_2018['CVDSTRK3'] = selected_data_2018['CVDSTRK3'].replace({2:0})
selected_data_2018 = selected_data_2018[selected_data_2018['CVDSTRK3'] != 7]
selected_data_2018 = selected_data_2018[selected_data_2018['CVDSTRK3'] != 9]
selected_data_2018['CVDSTRK3'] = selected_data_2018['CVDSTRK3'].astype('category')
selected_data_2018['CVDSTRK3'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [46]:
selected_data_2018['ADDEPEV2'] = selected_data_2018['ADDEPEV2'].replace({2:0})
selected_data_2018 = selected_data_2018[selected_data_2018['ADDEPEV2'] != 7]
selected_data_2018 = selected_data_2018[selected_data_2018['ADDEPEV2'] != 9]
selected_data_2018['ADDEPEV2'] = selected_data_2018['ADDEPEV2'].astype('category')
selected_data_2018['ADDEPEV2'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [47]:
selected_data_2018['CHCKDNY1'] = selected_data_2018['CHCKDNY1'].replace({2:0})
selected_data_2018 = selected_data_2018[selected_data_2018['CHCKDNY1'] != 7]
selected_data_2018 = selected_data_2018[selected_data_2018['CHCKDNY1'] != 9]
selected_data_2018['CHCKDNY1'] = selected_data_2018['CHCKDNY1'].astype('category')
selected_data_2018['CHCKDNY1'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [48]:
selected_data_2018['DIABETE3'] = selected_data_2018['DIABETE3'].replace({2:0, 3:0, 1:1, 4:1})
selected_data_2018 = selected_data_2018[selected_data_2018['DIABETE3'] != 7]
selected_data_2018 = selected_data_2018[selected_data_2018['DIABETE3'] != 9]
selected_data_2018['DIABETE3'] = selected_data_2018['DIABETE3'].astype('category')
selected_data_2018['DIABETE3'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [49]:
selected_data_2018['_DRDXAR1'] = selected_data_2018['_DRDXAR1'].replace({2:0})
selected_data_2018['_DRDXAR1'] = selected_data_2018['_DRDXAR1'].astype('category')
selected_data_2018['_DRDXAR1'].unique()

[1.0, 0.0]
Categories (2, float64): [0.0, 1.0]

In [50]:
selected_data_2018  = selected_data_2018[selected_data_2018['CHECKUP1'] != 7]
selected_data_2018  = selected_data_2018[selected_data_2018['CHECKUP1'] != 8]
selected_data_2018  = selected_data_2018[selected_data_2018['CHECKUP1'] != 9]
selected_data_2018['CHECKUP1'] = selected_data_2018['CHECKUP1'].astype('category')
selected_data_2018['CHECKUP1'].unique()

[1.0, 2.0, 3.0, 4.0]
Categories (4, float64): [1.0, 2.0, 3.0, 4.0]

In [51]:
selected_data_2018['PDIABTST'] = selected_data_2018['PDIABTST'].replace({2:0})
selected_data_2018 = selected_data_2018[selected_data_2018['PDIABTST'] != 7]
selected_data_2018 = selected_data_2018[selected_data_2018['PDIABTST'] != 9]
selected_data_2018['PDIABTST'] = selected_data_2018['PDIABTST'].astype('category')
selected_data_2018.PDIABTST.unique()

[1.0, 0.0]
Categories (2, float64): [0.0, 1.0]

In [52]:
selected_data_2018['_TOTINDA'] = selected_data_2018['_TOTINDA'].replace({2:0})
selected_data_2018 = selected_data_2018[selected_data_2018['_TOTINDA'] != 9]
selected_data_2018['_TOTINDA'] = selected_data_2018['_TOTINDA'].astype('category')
selected_data_2018['_TOTINDA'].unique()

[0, 1]
Categories (2, int64): [0, 1]

In [53]:
selected_data_2018 = selected_data_2018[selected_data_2018['_SMOKER3'] != 9]
selected_data_2018['_SMOKER3'] = selected_data_2018['_SMOKER3'].astype('category')
selected_data_2018['_SMOKER3'].unique()

[4, 1, 3, 2]
Categories (4, int64): [1, 2, 3, 4]

In [54]:
selected_data_2018['_RFDRHV6'] = selected_data_2018['_RFDRHV6'].replace({2:0})
selected_data_2018 = selected_data_2018[selected_data_2018['_RFDRHV6'] != 9]
selected_data_2018['_RFDRHV6'] = selected_data_2018['_RFDRHV6'].astype('category')
selected_data_2018['_RFDRHV6'].unique()

[1, 0]
Categories (2, int64): [0, 1]

In [55]:
selected_data_2018['CHCOCNCR'] = selected_data_2018['CHCOCNCR'].replace({2:0})
selected_data_2018 = selected_data_2018[selected_data_2018['CHCOCNCR'] != 7]
selected_data_2018 = selected_data_2018[selected_data_2018['CHCOCNCR'] != 9]
selected_data_2018['CHCOCNCR'] = selected_data_2018['CHCOCNCR'].astype('category')
selected_data_2018['CHCOCNCR'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [56]:
selected_data_2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 137399 entries, 0 to 437435
Data columns (total 24 columns):
 #   Column    Non-Null Count   Dtype   
---  ------    --------------   -----   
 0   _AGE_G    137399 non-null  category
 1   SEX1      137399 non-null  category
 2   HTM4      137399 non-null  float64 
 3   WTKG3     137399 non-null  float64 
 4   _BMI5     137399 non-null  float64 
 5   MARITAL   137399 non-null  category
 6   _INCOMG   137399 non-null  category
 7   _EDUCAG   137399 non-null  category
 8   GENHLTH   137399 non-null  category
 9   PHYSHLTH  137399 non-null  float64 
 10  MENTHLTH  137399 non-null  float64 
 11  SLEPTIM1  137399 non-null  float64 
 12  _SMOKER3  137399 non-null  category
 13  _MICHD    137399 non-null  category
 14  CVDSTRK3  137399 non-null  category
 15  ADDEPEV2  137399 non-null  category
 16  CHCKDNY1  137399 non-null  category
 17  CHCOCNCR  137399 non-null  category
 18  _DRDXAR1  137399 non-null  category
 19  CHECKUP1  137399 non-nu

### Cleaning the 2020 Dataset

In [57]:
# Importing raw data in csv format
raw_data_2020 = pd.read_csv('Data/2020_Data.csv', index_col = 0)
raw_data_2020.head()

X_STATE  FMONTH    IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
1        1       1  1042020       1     4   2020      1100  2020000001   
2        1       1  2072020       2     7   2020      1200  2020000002   
3        1       1  1232020       1    23   2020      1100  2020000003   
4        1       1  1092020       1     9   2020      1100  2020000004   
5        1       1  1042020       1     4   2020      1100  2020000005   

        X_PSU  CTELENM1  ...  X_RFPSA23  X_CLNSCPY  X_SGMSCPY  X_SGMS10Y  \
1  2020000001       1.0  ...        NaN        1.0        3.0        3.0   
2  2020000002       1.0  ...        NaN        NaN        NaN        NaN   
3  2020000003       1.0  ...        NaN        1.0        3.0        3.0   
4  2020000004       1.0  ...        NaN        NaN        NaN        NaN   
5  2020000005       1.0  ...        NaN        NaN        NaN        NaN   

   X_RFBLDS4  X_STOLDNA  X_VIRCOLN  X_SBONTIM  X_CRCREC1  X_AIDTST4  
1        3.0        3.0        3.0        3.0        1.0        1.0  
2        NaN        NaN        NaN        2.0        NaN        NaN  
3        3.0        3.0        3.0        3.0        1.0        2.0  
4        NaN        NaN        NaN        NaN        NaN        2.0  
5        NaN        NaN        NaN        NaN        NaN        9.0  

[5 rows x 279 columns]

In [58]:
raw_data_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 401958 entries, 1 to 401958
Columns: 279 entries, X_STATE to X_AIDTST4
dtypes: float64(234), int64(45)
memory usage: 858.7 MB


In [59]:
# Data is filtered based on variables chosen
selected_data_2020  =  raw_data_2020[['X_AGE_G'   , 'X_SEX'    , 'HTM4'      , 'WTKG3'    , 'X_BMI5'   , 'MARITAL' ,
                                      'X_INCOMG'  , 'X_EDUCAG' , 'GENHLTH'   , 'PHYSHLTH' , 'MENTHLTH' , 'SLEPTIM1',
                                      'X_SMOKER3' , 'X_MICHD'  , 'CVDSTRK3'  , 'ADDEPEV3' , 'CHCKDNY2' , 'CHCOCNCR',
                                      'X_DRDXAR2' , 'CHECKUP1' , 'X_RFDRHV7' , 'PDIABTST' , 'X_TOTINDA', 'DIABETE4']]

In [60]:
# The rows that contains null values are removed
selected_data_2020 = selected_data_2020.dropna()
selected_data_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 195322 entries, 2 to 401958
Data columns (total 24 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   X_AGE_G    195322 non-null  int64  
 1   X_SEX      195322 non-null  int64  
 2   HTM4       195322 non-null  float64
 3   WTKG3      195322 non-null  float64
 4   X_BMI5     195322 non-null  float64
 5   MARITAL    195322 non-null  float64
 6   X_INCOMG   195322 non-null  int64  
 7   X_EDUCAG   195322 non-null  int64  
 8   GENHLTH    195322 non-null  float64
 9   PHYSHLTH   195322 non-null  float64
 10  MENTHLTH   195322 non-null  float64
 11  SLEPTIM1   195322 non-null  float64
 12  X_SMOKER3  195322 non-null  int64  
 13  X_MICHD    195322 non-null  float64
 14  CVDSTRK3   195322 non-null  float64
 15  ADDEPEV3   195322 non-null  float64
 16  CHCKDNY2   195322 non-null  float64
 17  CHCOCNCR   195322 non-null  float64
 18  X_DRDXAR2  195322 non-null  float64
 19  CHECKUP1   195322 non-n

#### Cleaning each variable

In [61]:
selected_data_2020['X_AGE_G'] = selected_data_2020['X_AGE_G'].astype('category')
selected_data_2020['X_AGE_G'].unique()

[6, 3, 5, 4, 1, 2]
Categories (6, int64): [1, 2, 3, 4, 5, 6]

In [62]:
selected_data_2020['X_SEX'] = selected_data_2020['X_SEX'].replace({2:0})
selected_data_2020['X_SEX'] = selected_data_2020['X_SEX'].astype('category')
selected_data_2020['X_SEX'].unique()

[0, 1]
Categories (2, int64): [0, 1]

In [63]:
selected_data_2020['HTM4'].unique()

array([163., 168., 180., 160., 155., 183., 152., 150., 185., 175., 170.,
       157., 173., 178., 188., 145., 165., 191., 193., 201., 196., 198.,
       206., 147., 142., 203., 137., 132., 122., 124., 140., 162., 182.,
       161., 120., 153., 190., 172., 144., 105., 106., 169., 187., 176.,
       166., 154., 135., 167., 177., 127., 208., 213., 159., 211.,  91.,
       119.,  99., 216., 146., 130., 171., 156., 164., 158., 174., 125.,
       104., 151., 114., 110., 148., 101., 195., 138., 107., 229., 126.,
       189., 186., 218., 141., 149., 117., 109., 102., 179., 103., 128.,
       123., 108., 234., 100., 209.,  97., 139.])

In [64]:
selected_data_2020['WTKG3'] = selected_data_2020['WTKG3'].div(100).round(0)
selected_data_2020['WTKG3'].unique()

array([ 77.,  57.,  68.,  74.,  61.,  64., 136.,  67.,  59.,  73.,  51.,
       109.,  66.,  82.,  75.,  86.,  47., 100.,  63.,  54.,  84., 104.,
        79.,  70.,  72.,  88.,  52., 111.,  71.,  58., 108.,  78., 118.,
        76.,  91.,  97., 113.,  69.,  50.,  56.,  87.,  53., 175., 132.,
        95., 122.,  55.,  48.,  81.,  85., 102.,  65.,  92.,  45.,  98.,
        49.,  83.,  60.,  96.,  89.,  80., 134., 101.,  62., 145.,  93.,
        90., 103.,  94., 135., 121., 125.,  44.,  41., 120., 129., 126.,
       131., 107., 181., 194., 127., 110.,  99.,  39., 116., 105., 147.,
       141., 119., 128., 159.,  35., 117., 143., 112., 106., 172., 150.,
       190.,  42., 115., 156., 123., 138., 137.,  43., 130., 161.,  38.,
       170.,  46., 124., 177., 144., 114., 155., 154., 163.,  36.,  32.,
       192., 158., 152., 209., 166., 168.,  37., 142., 133., 139.,  40.,
       195.,  34., 173., 193., 164., 148., 140., 213., 230., 204., 149.,
       169., 146., 218., 160., 272., 200., 151., 15

In [65]:
selected_data_2020['X_BMI5'] = selected_data_2020['X_BMI5'].div(100).round(0)
selected_data_2020['X_BMI5'].unique()

array([29., 20., 24., 22., 26., 41., 28., 23., 18., 21., 34., 32., 25.,
       27., 31., 19., 39., 30., 33., 35., 44., 36., 59., 45., 17., 38.,
       43., 47., 49., 37., 52., 42., 15., 51., 55., 40., 50., 76., 16.,
       48., 46., 53., 82., 12., 14., 60., 67., 56., 63., 54., 66., 13.,
       57., 64., 58., 62., 83., 81., 68., 73., 90., 61., 71., 77., 87.,
       80., 69., 65., 75., 78., 70., 74., 86., 72., 79., 84., 92., 95.,
       88.])

In [66]:
selected_data_2020 = selected_data_2020[selected_data_2020['MARITAL'] != 9]
selected_data_2020['MARITAL'] = selected_data_2020['MARITAL'].astype('category')
selected_data_2020['MARITAL'].unique()

C:\Users\Shan\anaconda3\lib\site-packages\pandas\io\formats\format.py:1429: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  for val, m in zip(values.ravel(), mask.ravel())


[3.0, 1.0, 2.0, 5.0, 4.0, 6.0]
Categories (6, float64): [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [67]:
selected_data_2020 = selected_data_2020[selected_data_2020['X_INCOMG'] != 9]
selected_data_2020['X_INCOMG'] = selected_data_2020['X_INCOMG'].astype('category')
selected_data_2020['X_INCOMG'].unique()

[4, 5, 2, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 5]

In [68]:
selected_data_2020 = selected_data_2020[selected_data_2020['X_EDUCAG'] != 9]
selected_data_2020['X_EDUCAG'] = selected_data_2020['X_EDUCAG'].astype('category')
selected_data_2020['X_EDUCAG'].unique()

[2, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]

In [69]:
selected_data_2020 = selected_data_2020[selected_data_2020['GENHLTH'] != 7]
selected_data_2020 = selected_data_2020[selected_data_2020['GENHLTH'] != 9]
selected_data_2020['GENHLTH'] = selected_data_2020['GENHLTH'].astype('category')
selected_data_2020['GENHLTH'].unique()

[3.0, 2.0, 4.0, 1.0, 5.0]
Categories (5, float64): [1.0, 2.0, 3.0, 4.0, 5.0]

In [70]:
selected_data_2020 = selected_data_2020[selected_data_2020['MENTHLTH'] != 77]
selected_data_2020['MENTHLTH'] = selected_data_2020['MENTHLTH'].replace({88:0})
selected_data_2020 = selected_data_2020[selected_data_2020['MENTHLTH'] != 99]
selected_data_2020['MENTHLTH'].unique()

array([ 0., 30.,  2., 15.,  8.,  4.,  5., 10.,  3., 14., 20.,  1.,  7.,
       24., 25., 28., 16., 17.,  9., 12., 18.,  6., 29., 23., 21., 26.,
       27., 22., 13., 11., 19.])

In [71]:
selected_data_2020 = selected_data_2020[selected_data_2020['PHYSHLTH'] != 77]
selected_data_2020['PHYSHLTH'] = selected_data_2020['PHYSHLTH'].replace({88:0})
selected_data_2020 = selected_data_2020[selected_data_2020['PHYSHLTH'] != 99]
selected_data_2020['PHYSHLTH'].unique()

array([ 0., 28., 15.,  7.,  1.,  5., 30., 21.,  4.,  3.,  2., 20., 14.,
       18.,  6., 10., 25., 27., 17.,  8., 12., 23., 16., 19., 29.,  9.,
       26., 22., 11., 13., 24.])

In [72]:
selected_data_2020 = selected_data_2020[selected_data_2020['SLEPTIM1'] != 77]
selected_data_2020 = selected_data_2020[selected_data_2020['SLEPTIM1'] != 99]
selected_data_2020['SLEPTIM1'].unique()

array([ 6.,  8.,  4.,  5., 10.,  7.,  9.,  1., 12.,  3.,  2., 15., 16.,
       18., 14., 11., 20., 13., 24., 22., 17., 19., 23.])

In [73]:
selected_data_2020['X_MICHD'] = selected_data_2020['X_MICHD'].replace({2:0})
selected_data_2020['X_MICHD'] = selected_data_2020['X_MICHD'].astype('category')
selected_data_2020['X_MICHD'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [74]:
selected_data_2020 = selected_data_2020[selected_data_2020['CVDSTRK3'] != 7]
selected_data_2020 = selected_data_2020[selected_data_2020['CVDSTRK3'] != 9]
selected_data_2020['CVDSTRK3'] = selected_data_2020['CVDSTRK3'].replace({2:0})
selected_data_2020['CVDSTRK3'] = selected_data_2020['CVDSTRK3'].astype('category')
selected_data_2020['CVDSTRK3'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [75]:
selected_data_2020 = selected_data_2020[selected_data_2020['ADDEPEV3'] != 7]
selected_data_2020 = selected_data_2020[selected_data_2020['ADDEPEV3'] != 9]
selected_data_2020['ADDEPEV3'] = selected_data_2020['ADDEPEV3'].replace({2:0})
selected_data_2020['ADDEPEV3'] = selected_data_2020['ADDEPEV3'].astype('category')
selected_data_2020['ADDEPEV3'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [76]:
selected_data_2020 = selected_data_2020[selected_data_2020['CHCKDNY2'] != 7]
selected_data_2020 = selected_data_2020[selected_data_2020['CHCKDNY2'] != 9]
selected_data_2020['CHCKDNY2'] = selected_data_2020['CHCKDNY2'].replace({2:0})
selected_data_2020['CHCKDNY2'] = selected_data_2020['CHCKDNY2'].astype('category')
selected_data_2020['CHCKDNY2'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [77]:
selected_data_2020['DIABETE4'] = selected_data_2020['DIABETE4'].replace({2:0, 3:0, 1:2, 4:1})
selected_data_2020 = selected_data_2020[selected_data_2020['DIABETE4'] != 7]
selected_data_2020 = selected_data_2020[selected_data_2020['DIABETE4'] != 9]
selected_data_2020['DIABETE4'] = selected_data_2020['DIABETE4'].astype('category')
selected_data_2020['DIABETE4'].unique()

[0.0, 1.0, 2.0]
Categories (3, float64): [0.0, 1.0, 2.0]

In [78]:
selected_data_2020['X_DRDXAR2'] = selected_data_2020['X_DRDXAR2'].replace({2:0})
selected_data_2020['X_DRDXAR2'] = selected_data_2020['X_DRDXAR2'].astype('category')
selected_data_2020['X_DRDXAR2'].unique()

[0.0, 1.0]
Categories (2, float64): [0.0, 1.0]

In [80]:
selected_data_2020 = selected_data_2020[selected_data_2020['CHECKUP1'] != 7]
selected_data_2020 = selected_data_2020[selected_data_2020['CHECKUP1'] != 8]
selected_data_2020 = selected_data_2020[selected_data_2020['CHECKUP1'] != 9]
selected_data_2020['CHECKUP1'] = selected_data_2020['CHECKUP1'].astype('category')
selected_data_2020['CHECKUP1'].unique()

[1.0, 3.0, 2.0, 4.0]
Categories (4, float64): [1.0, 2.0, 3.0, 4.0]

In [81]:
selected_data_2020['PDIABTST'] = selected_data_2020['PDIABTST'].replace({2:0})
selected_data_2020 = selected_data_2020[selected_data_2020['PDIABTST'] != 7]
selected_data_2020 = selected_data_2020[selected_data_2020['PDIABTST'] != 9]
selected_data_2020['PDIABTST'] = selected_data_2020['PDIABTST'].astype('category')
selected_data_2020['PDIABTST'].unique()

[1.0, 0.0]
Categories (2, float64): [0.0, 1.0]

In [82]:
selected_data_2020['X_TOTINDA'] = selected_data_2020['X_TOTINDA'].replace({2:0})
selected_data_2020 = selected_data_2020[selected_data_2020['X_TOTINDA'] != 9]
selected_data_2020['X_TOTINDA'] = selected_data_2020['X_TOTINDA'].astype('category')
selected_data_2020['X_TOTINDA'].unique()

[0, 1]
Categories (2, int64): [0, 1]

In [83]:
selected_data_2020 = selected_data_2020[selected_data_2020['X_SMOKER3'] != 9]
selected_data_2020['X_SMOKER3'] = selected_data_2020['X_SMOKER3'].astype('category')
selected_data_2020['X_SMOKER3'].unique()

[4, 3, 1, 2]
Categories (4, int64): [1, 2, 3, 4]

In [84]:
selected_data_2020['X_RFDRHV7'] = selected_data_2020['X_RFDRHV7'].replace({2:0})
selected_data_2020 = selected_data_2020[selected_data_2020['X_RFDRHV7'] != 9]
selected_data_2020['X_RFDRHV7'] = selected_data_2020['X_RFDRHV7'].astype('category')
selected_data_2020['X_RFDRHV7'].unique()

[1, 0]
Categories (2, int64): [0, 1]

In [85]:
selected_data_2020['CHCOCNCR'] = selected_data_2020['CHCOCNCR'].replace({2:0})
selected_data_2020 = selected_data_2020[selected_data_2020['CHCOCNCR'] != 7]
selected_data_2020 = selected_data_2020[selected_data_2020['CHCOCNCR'] != 9]
selected_data_2020['CHCOCNCR'] = selected_data_2020['CHCOCNCR'].astype('category')
selected_data_2020['CHCOCNCR'].unique()

[1.0, 0.0]
Categories (2, float64): [0.0, 1.0]

In [86]:
selected_data_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 144844 entries, 7 to 401956
Data columns (total 24 columns):
 #   Column     Non-Null Count   Dtype   
---  ------     --------------   -----   
 0   X_AGE_G    144844 non-null  category
 1   X_SEX      144844 non-null  category
 2   HTM4       144844 non-null  float64 
 3   WTKG3      144844 non-null  float64 
 4   X_BMI5     144844 non-null  float64 
 5   MARITAL    144844 non-null  category
 6   X_INCOMG   144844 non-null  category
 7   X_EDUCAG   144844 non-null  category
 8   GENHLTH    144844 non-null  category
 9   PHYSHLTH   144844 non-null  float64 
 10  MENTHLTH   144844 non-null  float64 
 11  SLEPTIM1   144844 non-null  float64 
 12  X_SMOKER3  144844 non-null  category
 13  X_MICHD    144844 non-null  category
 14  CVDSTRK3   144844 non-null  category
 15  ADDEPEV3   144844 non-null  category
 16  CHCKDNY2   144844 non-null  category
 17  CHCOCNCR   144844 non-null  category
 18  X_DRDXAR2  144844 non-null  category
 19  CH

### Renaming the variables

In [87]:
selected_data_2016 = selected_data_2016.rename(columns = {'_AGE_G'  :'Age Category', 'SEX':'Sex', 'HTM4':'Height', 
                                                'WTKG3'    :'Weight', '_BMI5':'BMI',
                                                '_INCOMG' :'Income Category', '_EDUCAG':"Education Level", 
                                                'GENHLTH'  :'General Health', 'PHYSHLTH':'Physical Health','MENTHLTH':'Mental Health',  
                                                'SLEPTIM1' :'Total Sleep', 'MARITAL':'Marital Status',
                                                '_MICHD'  :'Coronary Heart Disease/Myocardial Infarction', 'CVDSTRK3':'Stroke', 'ADDEPEV2':'Depressive Disorder', 'CHCKIDNY':'Kidney Disease', 
                                                'DIABETE3' :'Diabetes', '_DRDXAR1':'Arthritis', 'CHECKUP1':'Time since last routine checkup',
                                                'PDIABTST' :'High blood sugar/Diabetes Test','_TOTINDA':'Workout','_SMOKER3':'Smoker Status',
                                                '_RFDRHV5':'Heavy Drinker','CHCOCNCR':'Cancer'})

In [88]:
selected_data_2018 = selected_data_2018.rename(columns = {'_AGE_G'  :'Age Category', 'SEX1':'Sex', 'HTM4':'Height', 
                                                'WTKG3'    :'Weight', '_BMI5':'BMI', 'INCOME2':'Income Level',
                                                '_INCOMG' :'Income Category', '_EDUCAG':"Education Level", 
                                                'GENHLTH'  :'General Health', 'PHYSHLTH':'Physical Health','MENTHLTH':'Mental Health',  
                                                'SLEPTIM1' :'Total Sleep', 'MARITAL':'Marital Status',
                                                '_MICHD'  :'Coronary Heart Disease/Myocardial Infarction', 'CVDSTRK3':'Stroke', 'ADDEPEV2':'Depressive Disorder', 'CHCKDNY1':'Kidney Disease', 
                                                'DIABETE3' :'Diabetes', '_DRDXAR1':'Arthritis', 'CHECKUP1':'Time since last routine checkup',
                                                'PDIABTST' :'High blood sugar/Diabetes Test','_TOTINDA':'Workout','_SMOKER3':'Smoker Status',
                                                '_RFDRHV6':'Heavy Drinker','CHCOCNCR':'Cancer'})

In [89]:
selected_data_2020 = selected_data_2020.rename(columns = {'X_AGE_G'  :'Age Category', 'X_SEX':'Sex', 'HTM4':'Height', 
                                                'WTKG3'    :'Weight', 'X_BMI5':'BMI', 'INCOME2':'Income Level',
                                                'X_INCOMG' :'Income Category', 'X_EDUCAG':"Education Level", 
                                                'GENHLTH'  :'General Health', 'PHYSHLTH':'Physical Health','MENTHLTH':'Mental Health',  
                                                'SLEPTIM1' :'Total Sleep', 'MARITAL':'Marital Status',
                                                'X_MICHD'  :'Coronary Heart Disease/Myocardial Infarction', 'CVDSTRK3':'Stroke', 'ADDEPEV3':'Depressive Disorder', 'CHCKDNY2':'Kidney Disease', 
                                                'DIABETE4' :'Diabetes', 'X_DRDXAR2':'Arthritis', 'CHECKUP1':'Time since last routine checkup',
                                                'PDIABTST' :'High blood sugar/Diabetes Test','X_TOTINDA':'Workout','X_SMOKER3':'Smoker Status',
                                                'X_RFDRHV7':'Heavy Drinker','CHCOCNCR':'Cancer'})

In [90]:
selected_data_2016.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 132556 entries, 1 to 486302
Data columns (total 24 columns):
 #   Column                                        Non-Null Count   Dtype   
---  ------                                        --------------   -----   
 0   Age Category                                  132556 non-null  category
 1   Sex                                           132556 non-null  int64   
 2   Height                                        132556 non-null  float64 
 3   Weight                                        132556 non-null  float64 
 4   BMI                                           132556 non-null  float64 
 5   Marital Status                                132556 non-null  category
 6   Income Category                               132556 non-null  category
 7   Education Level                               132556 non-null  category
 8   General Health                                132556 non-null  category
 9   Physical Health                      

In [91]:
selected_data_2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 137399 entries, 0 to 437435
Data columns (total 24 columns):
 #   Column                                        Non-Null Count   Dtype   
---  ------                                        --------------   -----   
 0   Age Category                                  137399 non-null  category
 1   Sex                                           137399 non-null  category
 2   Height                                        137399 non-null  float64 
 3   Weight                                        137399 non-null  float64 
 4   BMI                                           137399 non-null  float64 
 5   Marital Status                                137399 non-null  category
 6   Income Category                               137399 non-null  category
 7   Education Level                               137399 non-null  category
 8   General Health                                137399 non-null  category
 9   Physical Health                      

In [92]:
selected_data_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 144844 entries, 7 to 401956
Data columns (total 24 columns):
 #   Column                                        Non-Null Count   Dtype   
---  ------                                        --------------   -----   
 0   Age Category                                  144844 non-null  category
 1   Sex                                           144844 non-null  category
 2   Height                                        144844 non-null  float64 
 3   Weight                                        144844 non-null  float64 
 4   BMI                                           144844 non-null  float64 
 5   Marital Status                                144844 non-null  category
 6   Income Category                               144844 non-null  category
 7   Education Level                               144844 non-null  category
 8   General Health                                144844 non-null  category
 9   Physical Health                      

### Merging the datasets

In [93]:
selected_datas = [selected_data_2016, selected_data_2018, selected_data_2020]
selected_data = pd.concat(selected_datas)
selected_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 414799 entries, 1 to 401956
Data columns (total 24 columns):
 #   Column                                        Non-Null Count   Dtype   
---  ------                                        --------------   -----   
 0   Age Category                                  414799 non-null  category
 1   Sex                                           414799 non-null  int64   
 2   Height                                        414799 non-null  float64 
 3   Weight                                        414799 non-null  float64 
 4   BMI                                           414799 non-null  float64 
 5   Marital Status                                414799 non-null  category
 6   Income Category                               414799 non-null  category
 7   Education Level                               414799 non-null  category
 8   General Health                                414799 non-null  category
 9   Physical Health                      

In [95]:
selected_datas = [selected_data_2016, selected_data_2018, selected_data_2020]
selected_data = pd.concat(selected_datas)
selected_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 414799 entries, 1 to 401956
Data columns (total 24 columns):
 #   Column                                        Non-Null Count   Dtype   
---  ------                                        --------------   -----   
 0   Age Category                                  414799 non-null  category
 1   Sex                                           414799 non-null  int64   
 2   Height                                        414799 non-null  float64 
 3   Weight                                        414799 non-null  float64 
 4   BMI                                           414799 non-null  float64 
 5   Marital Status                                414799 non-null  category
 6   Income Category                               414799 non-null  category
 7   Education Level                               414799 non-null  category
 8   General Health                                414799 non-null  category
 9   Physical Health                      

### Exporting merged dataset to csv file

In [96]:
selected_data.to_csv("Data/selected_data.csv")